name: dev_deploy
on:
  push:
    branches: 
     
  workflow_dispatch:

jobs:
  build-and-run:
   runs-on: ubuntu-latest


   steps:
   - name: checkout repository
     uses: actions/checkout@v4


   - name: set-up docker
     uses: docker/setup-buildx-action@v2 


   - name: build docker image 
     run: |
         docker build -t attandence:latest .
   - name: tag docker image
     run : |
       dokcer tag 
          

   - name: show  docker image 
     run: | 
      docker images

   - name: run docker image
     run: |
       docker run -d -p 5000:5000 attandence:latest   
